blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/{{REPO_OWNER}}/{{PROJECT_NAME}}/discussions
    about: For open-ended questions, use Discussions instead of an issue.
